const rabbits = [
  {
    name: "Jericho",
    started: "Januaray 2017",
    breed: "Dutch Hopper",
    inspiration: "a selection of ideas",
    hqSrc: "./rabbits/high-quality/painting-1.png",
    lqSrc: "./rabbits/low-quality/painting-1.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Ruby",
    started: "Tuesday, March 2nd",
    breed: "Holland Lop",
    inspiration: "every other Tuesday",
    hqSrc: "./rabbits/high-quality/painting-2.png",
    lqSrc: "./rabbits/low-quality/painting-2.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Brian",
    started: "s quiet Sunday afternoon",
    breed: "Netherland Dwarf",
    inspiration: "the original Fast and Furious",
    hqSrc: "./rabbits/high-quality/painting-3.png",
    lqSrc: "./rabbits/low-quality/painting-3.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Zillionaire Cannon",
    started: "before I should have",
    breed: "Eastern Rabbitbun",
    inspiration: "Americas Got Talent S04E17",
    hqSrc: "./rabbits/high-quality/painting-7.png",
    lqSrc: "./rabbits/low-quality/painting-7.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Karenaoke",
    started: "while on the couch",
    breed: "Pygmy Bouncer",
    inspiration: "traffic circles",
    hqSrc: "./rabbits/high-quality/painting-8.png",
    lqSrc: "./rabbits/low-quality/painting-8.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Jerimander",
    started: "when I felt like it",
    breed: "Rex Imperius",
    inspiration: "a lonely walk on the pier",
    hqSrc: "./rabbits/high-quality/painting-9.png",
    lqSrc: "./rabbits/low-quality/painting-9.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Goranthize",
    started: "After a long sunrise",
    breed: "Tuesday Groaner",
    inspiration: "mother in laws",
    hqSrc: "./rabbits/high-quality/painting-10.png",
    lqSrc: "./rabbits/low-quality/painting-10.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Brucaniel",
    started: "one sunny afternoon",
    breed: "Riverian Ouncemaker",
    inspiration: "making breakfast",
    hqSrc: "./rabbits/high-quality/painting-11.png",
    lqSrc: "./rabbits/low-quality/painting-11.jpg",
    price: "100",
    size: "8x10",
  },

  {
    name: "Brucaniel",
    started: "one sunny afternoon",
    breed: "Riverian Ouncemaker",
    inspiration: "making breakfast",
    hqSrc: "./rabbits/high-quality/painting-11.png",
    lqSrc: "./rabbits/low-quality/painting-11.jpg",
    price: "100",
    size: "8x10",
  },

  {
    name: "Brucaniel",
    started: "one sunny afternoon",
    breed: "Riverian Ouncemaker",
    inspiration: "making breakfast",
    hqSrc: "./rabbits/high-quality/painting-11.png",
    lqSrc: "./rabbits/low-quality/painting-11.jpg",
    price: "100",
    size: "8x10",
  },

  //*************** */

  {
    name: "Brucaniel",
    started: "one sunny afternoon",
    breed: "Riverian Ouncemaker",
    inspiration: "making breakfast",
    hqSrc: "./rabbits/high-quality/painting-11.png",
    lqSrc: "./rabbits/low-quality/painting-11.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Brucaniel",
    started: "one sunny afternoon",
    breed: "Riverian Ouncemaker",
    inspiration: "making breakfast",
    hqSrc: "./rabbits/high-quality/painting-11.png",
    lqSrc: "./rabbits/low-quality/painting-11.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Brucaniel",
    started: "one sunny afternoon",
    breed: "Riverian Ouncemaker",
    inspiration: "making breakfast",
    hqSrc: "./rabbits/high-quality/painting-11.png",
    lqSrc: "./rabbits/low-quality/painting-11.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Brucaniel",
    started: "one sunny afternoon",
    breed: "Riverian Ouncemaker",
    inspiration: "making breakfast",
    hqSrc: "./rabbits/high-quality/painting-11.png",
    lqSrc: "./rabbits/low-quality/painting-11.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Brucaniel",
    started: "one sunny afternoon",
    breed: "Riverian Ouncemaker",
    inspiration: "making breakfast",
    hqSrc: "./rabbits/high-quality/painting-11.png",
    lqSrc: "./rabbits/low-quality/painting-11.jpg",
    price: "100",
    size: "8x10",
  },
  {
    name: "Brucaniel",
    started: "one sunny afternoon",
    breed: "Riverian Ouncemaker",
    inspiration: "making breakfast",
    hqSrc: "./rabbits/high-quality/painting-11.png",
    lqSrc: "./rabbits/low-quality/painting-11.jpg",
    price: "100",
    size: "8x10",
  },

  //*************** */
];

export { rabbits };
